name: test
on: [workflow_dispatch]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          sudo apt install libgl1-mesa-dev libglu1-mesa-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libpulse-dev -y
          git clone --single-branch --branch submodules --recurse-submodules https://github.com/player-03/lime.git lime
          haxelib dev lime lime
          haxelib --quiet install format
          haxelib --quiet install hxp
          haxelib --quiet install hxcpp
          haxelib --quiet install lime-samples
          haxelib --quiet install openfl 9.1.0
      - name: Setup Lime
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT /opt/hostedtoolcache/ndk/r15c/x64
          haxelib run lime config ANDROID_SETUP true
          haxelib run lime rebuild tools
          haxelib run lime rebuild android
          ls lime/ndll/Android
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: objects
          path: lime/project/obj
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: allobjects
          path: lime/project/all_objs
